### ISSUE TITLE
SECRET_KEY vizibil in repo, mai bine mutat in variabila de sistem

### ISSUE THREAD

**Issue by ionescu77** [IsabellaElena27/TropicalStudio-ManagementSystem#1]
Nu este rau...
Aici poate ar fi bine ca sa nu apara `SECRET_KEY`, mai ales intr-un repo public.
Dar este ok daca site-ul nu este in productie.

https://github.com/IsabellaElena27/TropicalStudio-ManagementSystem/blob/65eee9f896429b8f6dd208faec0c2d83a3fb514e/TropicalStudio/settings.py#L23

Exemplu 1 pentru `SECRET_KEY` din variabila de system in windows (ar trebui sa mearga si daca site-ul ruleaza pe linux):

https://www.youtube.com/watch?v=gPuTVosUzsw

**Comment by ionescu77** [comment]
Exermplu 2 cu `python-decouple`

https://www.youtube.com/watch?v=BuOlpKA2cNs

**Comment by IsabellaElena27** [comment]
@ionescu77 Mulțumesc pentru feedback! Site-ul nu este în producție, este un proiect dezvoltat pentru finalizarea unui curs, dar îmi doresc să-l îmbunătățesc pe parcurs. Apreciez sfatul și voi tine cont de el.

**Comment by ionescu77** [comment]
Super. Ok 😇 o sa inchid issue. Interesant si mult succes cu django.
